config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'show'
  post 'tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'
  patch '/tasks/:id', to: 'tasks#update', as: 'task'
  delete '/tasks/:id', to: 'tasks#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /task
  def index
    @tasks = Task.all
  end

  # GET /tasks/:id
  def show
    # set_task
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # POST /tasks
  def create
    task = Task.new(task_params)
    # task = Task.new(params[:task])
    # => will raise an ActiveRecord::ForbiddenAttributesError
    task.save

    redirect_to tasks_path
  end

  def edit
    # @task = Task.find(params[:id])
  end

  # PATCH /tasks/:id
  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <script src="https://use.fontawesome.com/releases/v5.10.1/js/all.js" data-auto-replace-svg="nest"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Title' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details, 'details' %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% if @task.id %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class="text-center">Tasks list</h1>


<div>
  <% @tasks.each do |task| %>
    <input type="checkbox"  id="title" name="title" <%= "checked" if task.completed %>>
    <label for="title">
      <%= link_to task.title, show_path(task) %>
    </label>

 <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-dumpster"></i>
    <% end %>

  <% end %>



</div>

 <%= link_to "Create Task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1 class="text-center">MY tasks</h1>
<div>
   <%= @task.details %>
</div>

<div>
    <input type="checkbox"  id="details" name="details"
    <%= "checked" if @task.completed %>>
    <p> This task is <%= "not" if !@task.completed %> completed </p>
</div>

<p> <%= link_to "Edit this task", tasks_edit_path %> </p>


   <%= link_to "return", tasks_path %>